const ACTION_TYPES = {
  GET_POWERS_ACTION: 'GET_POWERS_ACTION',
  GET_POWERS_REQUEST: 'GET_POWERS_REQUEST',
  GET_POWERS_SUCCESS: 'GET_POWERS_SUCCESS',
  GET_POWERS_ERROR: 'GET_POWERS_ERROR',

  CREATE_HERO_ACTION: 'CREATE_HERO_ACTION',
  CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
  CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
  CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',

  GET_HEROES_ACTION: 'GET_HEROES_ACTION',
  GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
  GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
  GET_HEROES_ERROR: 'GET_HEROES_ERROR',

  UPDATE_HERO_ACTION: 'UPDATE_HERO_ACTION',
  UPDATE_HERO_REQUEST: 'UPDATE_HERO_REQUEST',
  UPDATE_HERO_SUCCESS: 'UPDATE_HERO_SUCCESS',
  UPDATE_HERO_ERROR: 'UPDATE_HERO_ERROR',
};

export default ACTION_TYPES;
